# Generated by Django 5.0.1 on 2024-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaleEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guardian_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dob", models.DateField()),
                ("mobile_no", models.CharField(blank=True, max_length=10, null=True)),
                ("additional_mobile_no", models.CharField(blank=True, max_length=10)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=50, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("next_follow_up_date", models.DateField()),
                ("notes", models.TextField()),
                ("record_updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
